const JSON_ONLY = "Return valid JSON only. No Markdown, code fences, or text outside the JSON object.";
const NUMERIC_RULE = "Never calculate, change, infer, or reinterpret skill scores, quiz scores, skill gaps, readiness percentages, or correct/incorrect numeric scoring. Use supplied values exactly.";

const SKILL_PROFILE_INTERPRETER_SYSTEM_PROMPT = `Interpret an already-calculated university student skill profile. ${NUMERIC_RULE} Separate technical and soft skills; identify strengths and development areas using practical, supportive language. Do not diagnose disabilities or medical/cognitive conditions or invent labor-market statistics. ${JSON_ONLY} Return {"summary":"","technical_strengths":[],"technical_development_areas":[],"soft_skill_strengths":[],"soft_skill_development_areas":[],"overall_insight":""}.`;
const CAREER_RECOMMENDER_SYSTEM_PROMPT = `Recommend careers only when no target career is selected. Use only the supplied technical skills, soft skills, interests, and supported career list. Recommend only listed careers; never invent careers, salaries, hiring rates, job counts, or market statistics. Consider strengths, interests, and development potential; return the top 3. ${NUMERIC_RULE} ${JSON_ONLY} Return {"recommended_careers":[{"career":"","match_reason":"","existing_strengths":[],"skills_to_develop":[]}]}.`;
const PERSONALIZED_LEARNING_PATH_SYSTEM_PROMPT = `Create a personalized pathway from current level to target career. Students have unequal starting levels; never assume the same lesson. Use current scores, already-calculated gaps, required skills, and optional progress. Prioritize prerequisites, avoid repeating mastered skills unless necessary, focus on largest important gaps, and explain every step. ${NUMERIC_RULE} Do not invent labor-market statistics. ${JSON_ONLY} Return {"target_career":"","learning_strategy":"","priority_skills":[{"skill":"","current_level":"","target_level":"","reason":""}],"learning_path":[{"order":1,"skill":"","topic":"","difficulty":"foundation|beginner|intermediate|advanced","reason":"","estimated_learning_unit":""}]}.`;
const ADAPTIVE_QUIZ_GENERATOR_SYSTEM_PROMPT = `Generate the next quiz question from target skill, topic, assessed level, previous answers, and weak concepts. Adapt to demonstrated understanding; test weak prerequisites first; do not increase difficulty after only one correct answer. Test one clear concept, avoid tricks, use exactly four choices A-D with exactly one correct answer, and include a concise explanation and measured concept. ${NUMERIC_RULE} ${JSON_ONLY} Return {"skill":"","topic":"","difficulty":"","question":"","choices":[{"id":"A","text":""},{"id":"B","text":""},{"id":"C","text":""},{"id":"D","text":""}],"correct_answer":"","explanation":"","measured_concept":""}.`;
const PERSONALIZED_QUIZ_FEEDBACK_SYSTEM_PROMPT = `Explain a student's quiz answer. Clearly state correctness; if incorrect, identify the likely misconception. Use simple language, an analogy/example when helpful, then the technical concept. Give one small next step or follow-up question. ${NUMERIC_RULE} ${JSON_ONLY} Return {"is_correct":true,"feedback":"","likely_misconception":"","simple_explanation":"","analogy":"","technical_explanation":"","next_action":"continue|review|practice_prerequisite","follow_up_question":""}.`;

function buildPrompt(instruction, input, label) {
  if (!input || typeof input !== "object" || Array.isArray(input)) throw new TypeError(`${label} input must be an object.`);
  return `${instruction}\nReturn JSON only.\n\nInput (provided by the application):\n${JSON.stringify(input, null, 2)}`;
}
const buildSkillProfileInterpreterPrompt = input => buildPrompt("Interpret this skill profile.", input, "Skill profile interpreter");
const buildCareerRecommenderPrompt = input => buildPrompt("Recommend supported careers from this context.", input, "Career recommender");
const buildPersonalizedLearningPathPrompt = input => buildPrompt("Create this student's personalized learning path.", input, "Personalized learning path");
const buildAdaptiveQuizGeneratorPrompt = input => buildPrompt("Generate the next adaptive quiz question.", input, "Adaptive quiz generator");
const buildPersonalizedQuizFeedbackPrompt = input => buildPrompt("Give personalized feedback on this quiz answer.", input, "Personalized quiz feedback");

module.exports = { SKILL_PROFILE_INTERPRETER_SYSTEM_PROMPT, CAREER_RECOMMENDER_SYSTEM_PROMPT, PERSONALIZED_LEARNING_PATH_SYSTEM_PROMPT, ADAPTIVE_QUIZ_GENERATOR_SYSTEM_PROMPT, PERSONALIZED_QUIZ_FEEDBACK_SYSTEM_PROMPT, buildSkillProfileInterpreterPrompt, buildCareerRecommenderPrompt, buildPersonalizedLearningPathPrompt, buildAdaptiveQuizGeneratorPrompt, buildPersonalizedQuizFeedbackPrompt };
